/*
 * Lu @ 2012/11/05
 */
document.domain = 'tianya.cn';
var domain = window.location.host;
// top
(function(){var goTopBtn='<div class="btn-jumptop" id="jumpTop"><a href="#top" class="ico ico-top" title="&#36820;&#22238;&#39030;&#37096;"></a></div>';$("body").append(goTopBtn);$("#jumpTop").hide();$(window).scroll(function(){var sTop=document.body.scrollTop+document.documentElement.scrollTop;if(sTop>20){$("#jumpTop").show()}else{$("#jumpTop").hide()}});$("#jumpTop").click(function(){scroll("0",10)})})();
// toggle
(function(){$("#jVer").live('click',function(){$(this).toggleClass("sl");if($(this).hasClass("sl")){$("#jVer span").html("&#9650;")}else{$("#jVer span").html("&#9660;")}$("#jVerCon").toggle()});$("#jCat dd").hide();$("#jCat dd").first().show();$("#jCat dt").first().addClass("cl");$("#jCat dt").click(function(){$(this).toggleClass("cl");$(this).next("dd").siblings("dd").hide();$(this).siblings("dt").removeClass("cl");$(this).next("dd").toggle()});for(var i=10;i<$("#nav li").length;i++){$("#nav li:nth-child("+i+")").toggle()}$("#nav li").last().find("a").click(function(){$(this).toggleClass("sl");if($(this).hasClass("sl")){$(this).html("&#25910;&#36215;&#8593;")}else{$(this).html("&#26356;&#22810;&#8595;")}for(var i=10;i<$("#nav li").length;i++){$("#nav li:nth-child("+i+")").toggle()}return false})})();
// login
function login(){var bWidth=document.body.clientWidth;var bHeight=document.body.clientHeight;$("body").append('<div id="mask"></div>');$("#mask").css({height:bHeight});$("body").append('<div id="login" class="pop"><div class="warp fn-cf"><div class="ui-form ui-form-nor fn-cf"><div class="field-group field-group-tit"><input type="text" class="ui-text" required="required" name="user_name" id="user_name" placeholder="&#29992;&#25143;&#21517;" /></div><div class="field-group field-group-tit"><input type="password" class="ui-text" required="required" name="user_passwd" id="user_passwd" placeholder="&#23494;&#30721;" /></div><div class="field-group field-group-btn"><div class="field-c2"><input type="button" id="jLogClo" class="btn btn-l" value="&#21462;&#28040;" /></div><div class="field-c2"><input type="button" class="btn btn-l btn-blue" id="jLogBtn" value="&#30331;&#24405;" /></div></div></div></div></div>');$("#mask,#login").show();$("#jLogClo").click(function(){$("#mask,#login,#msg").remove()});$("#jLogBtn").click(function(){var uName=$("#user_name").val();var uPsd=$("#user_passwd").val();var uRfh=window.location.href;var isSubmit=true;$.each(["#user_name","#user_passwd"],function(){if(!validate($(this))){isSubmit=false}});if(isSubmit){$.post("http://"+domain+"/touch/I/user_logon.jsp",{"user_name":uName,"user_passwd":uPsd,"user_refresh":uRfh},function(dataObj){var data=eval("("+dataObj+")");if(!data.error_msg){$("#meta p").html('<a href="http://'+domain+'/touch/my/home.jsp">'+data.user_name+"</a>");$("#mask").toggle();$("#login").toggle()}else{if(data.error_msg=="0"){window.location.href="http://"+domain+"/touch/user/login.jsp?isvl=1";}else{$.msg("error",data.error_msg)}}})}else{$.msg("warning","&#35831;&#36755;&#20837;&#23436;&#25972;")}return isSubmit})}$("#jLog").click(function(){login()});
// msg type:warning/success/error/info
(function(){var msg='<div id="msg" class="ui-msg"><span class="ico ico-msg"></span><p></p></div>';$.msg=function(type,txt){$("body").append(msg);$("#msg").addClass("ui-msg-"+type);$("#msg p").html(txt);$("#msg").show();setTimeout(function(){$("#msg").remove()},(3000))}})();
// limit
(function(){$.fn.wordLimit=function(num){this.each(function(){if(!num){var copyThis=$(this.cloneNode(true)).hide().css({"position":"absolute","width":"auto","overflow":"visible"});$(this).after(copyThis);if(copyThis.width()>$(this).width()){$(this).text($(this).text().substring(0,$(this).text().length-4));$(this).html($(this).html());copyThis.remove();$(this).wordLimit()}else{copyThis.remove();return}}else{var maxwidth=num;if($(this).text().length>maxwidth){$(this).text($(this).text().substring(0,maxwidth));$(this).html($(this).html())}}})};$(".page-home .list-c1 li a").wordLimit(17);$(".media p small").wordLimit(24);$(".page-channel .list-c1 li a").wordLimit(17);$(".so-word a").wordLimit(4);$("#limit").each(function(){var txtL=$(this).text();if(txtL.length>100){var txtS=txtL.substring(0,100);$(this).text(txtS);$(this).append('&#8230;<a class="show" href="javascript:void(0);">&#26356;&#22810;&#9660;</a>')}$("#limit a.show").live("click",function(){$("#limit").text(txtL);$("#limit").append('<a class="hide" href="javascript:void(0);">&#25910;&#36215;&#9650;</a>')});$("#limit a.hide").live("click",function(){$("#limit").text(txtS);$("#limit").append('&#8230;<a class="show" href="javascript:void(0);">&#26356;&#22810;&#9660;</a>')})});$(".list-c1s li").bind("ontouchstart",function(){$(this).addClass("hover")}).bind("ontouchend",function(){$(this).removeClass("hover")})})();
// validate
function validate(id){var idVal=$(id).val();if(idVal.length>0){return true}else{return false}};
// img
(function(){$(".page-content .item img").each(function(){if($(this).attr("data-large").length>0){var src=$(this).attr("data-large");$(this).click(function(){window.open(src)})}})})();
